spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: dove
    password: dove@123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # Specify your desired Hibernate DDL behavior
  h2:
    console:
      enabled: true # Enable H2 console for development (optional)
      settings:
        web-allow-others: true # Allow other computers to connect to the H2 console (optional)
debug: true
